# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Codingdojo.org Hugo Template"
license = "MIT"
licenselink = "https://github.com/codingdojo-org/template-hugo-codingdojo/blob/master/LICENSE.md"
description = "a clean, css framework free template "
homepage = "https://github.com/codingdojo-org/template-hugo-codingdojo"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Rui Carvalho, Thomas Clavier"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
